### ISSUE TITLE
`TextMarshaler` colorization

### ISSUE THREAD

**Issue by hermannm** [neilotoole/jsoncolor#20]
Hi there! First off, great library. I was toying around with it for some debug logging, and was stumped when some of my values weren't colorized (shown below). Turns out that `calendar_interval` and `_key` are from [go-elasticsearch](https://github.com/elastic/go-elasticsearch/blob/v8.10.0/typedapi/types/enums/calendarinterval/calendarinterval.go#L27 "CalendarInterval implementation"), and that they have many enum-like structs implementing `encoding.TextMarshaler`.

![Screenshot from 2023-11-08 15-39-31](https://github.com/neilotoole/jsoncolor/assets/48361621/49b730b2-acd3-4186-b844-0ab5fabd855a)

Now, I understand that deducing and correctly colorizing the output from custom `TextMarshaler`s is impractical, but I'm wondering if you might be open to a different proposal: adding a `TextMarshaler` field to `Colors`, which can then be used in `encoder.encodeTextMarshaler`. That way, when dealing with a lot of `TextMarshaler` fields as in my case with Elasticsearch, the color output can still be customized.

If you're open to this, I'd be happy to put in a PR, as I've already dug around the codebase a little when figuring this out.

**Comment by neilotoole** [comment]
@hermannm Glad the lib is useful to you! 🙏

I hadn't remotely considered that use case. I'm totally open to a PR.

**Comment by hermannm** [comment]
@neilotoole Great to hear! Opened a PR now: #21
