### ISSUE TITLE
Fix legacy linting issues

### ISSUE THREAD

**Issue by neilotoole** [neilotoole/jsoncolor#24]
PR #23 enables `golangci-lint` linting in a GH workflow. There's a bunch of lint issues (e.g. see this [run](https://github.com/neilotoole/jsoncolor/actions/runs/6827302703)). Until the lint issues are addressed, the lint config (`.github/workflows/golangci-lint.yml`) doesn't fail the workflow (`--issues-exit-code=0`).

- [ ] Fix lint issues
- [ ] Set lint workflow to fail on any lint issues

**Comment by dreamjz** [comment]
I'll solve this.
Perhaps we can disable reporting long lines(`lll`) for golangci-lint ? 
I feel this may not be entirely necessary

**Comment by neilotoole** [comment]
Go for it!

Agreed re long lines.

Feel free to adjust other linters if it makes sense. The linting config obviously hasn't been tuned yet.

**Comment by neilotoole** [comment]
Linter reports no issues, closing issue. Thanks @dreamjz!
